optimizer: Adam
lr: 1e-4
epochs: 40
batch_size: 2
scheduler: cosine
min_lr: 1e-5
warmup_ratio: 0.05
grad_clip: 1.0
num_workers: 4
pin_memory: true
seed: 42
amp: true
grad_accum_steps: 4
validate_every_steps: 5




