optimizer: Adam
lr: 3e-4
betas: [0.9, 0.999]
weight_decay: 0.0
epochs: 5000
batch_size: 1
scheduler: none
min_lr: 1e-5
warmup_ratio: 0.0
grad_clip: 0.0
num_workers: 2
pin_memory: true
seed: 42
amp: false
grad_accum_steps: 1
validate_every_steps: 0


