# Run/meta
run_name: radio-txunet-optA-256
device: cuda
seed: 1337

# Precision/perf
amp: true
amp_autocast_dtype: fp16
use_grad_scaler: true
channels_last: true
allow_tf32: true
cudnn_benchmark: true

# Dataloader
batch_size: 16
num_workers: 8
pin_memory: true
persistent_workers: true
prefetch_factor: 2
drop_last: false

# Optimizer
optimizer: Adam
lr: 3.0e-4
betas: [0.9, 0.999]
weight_decay: 0.0

# Scheduler (per-optimizer-step)
scheduler: warmup_cosine
epochs: 60
min_lr: 3.0e-5
warmup_ratio: 0.05

# Training loop
grad_accum_steps: 1
grad_clip: 2.0
validate_every_steps: 0
skip_non_finite_batches: true
sanitize_train_loss: true

# Loss
loss: charbonnier
epsilon: 1.0e-3

# Checkpointing/logging
checkpoint_dir: checkpoints/radio_txunet_optA
tb_root: /tmp/mlsp_tb
save_every_n_epochs: 1
keep_last: 3
log_interval_steps: 50
log_lr: true
log_grad_norm: true
log_update_ratio: true


