_target_: src.schedulers.wsd_s.WSDScheduler

name: mlsp_sd_finetune_32
warmup_samples: 0
stable_samples:
  - 57600
decay_samples:
  - 38400
peak_lr: 0.0001
min_lr_factor: 0.01
last_epoch: -1
interval: step
frequency: 1
