_target_: src.schedulers.wsd_s.WSDScheduler

name: wsd_finetune_bs40
warmup_steps: 384
stable_steps:
  - 5376
decay_steps:
  - 1920
peak_lr: 0.0006
min_lr_factor: 0.05
last_epoch: -1
interval: step
frequency: 1
