_target_: src.schedulers.wsd_s.WSDScheduler

name: wsd_s_finetune_bs60
warmup_steps: 16
stable_steps:
  - 48
  - 64
  - 128
  - 256
  - 512
  - 1024
  - 2048
decay_steps:
  - 16
  - 16
  - 32
  - 64
  - 128
  - 256
  - 512
peak_lr: 0.0015
min_lr_factor: 0.0
last_epoch: -1
interval: step
frequency: 1
