icassp_task2_finetune:
  ckpt_path: null
  load_weights_only: False
  
  defaults:
    - trainer: default
    - datamodule: icassp_task2
    - optimizer: adam
    - scheduler: null
    - algorithm: indoor
    - network: txunet
    - callbacks: [ tqdm_progress_bar, model_checkpoint_0 ]
    - loggers: [ aim ]
    - strategy: null
    - _self_

  trainer:
    max_epochs: 100

  datamodule:
    train_samples_per_epoch: 3000

  callbacks:
    model_checkpoint_0:
      dirpath: runs/icassp_task2_finetune/checkpoints/hard

  loggers:
    aim:
      experiment: v3_icassp_task2_finetune

  algorithm:
    finetune:
      enable: True
      freeze_encoder_epochs: 0
      discriminative_lr:
        enable: True
      bn_recalibration:
        enable: True
      l2sp:
        enable: True
