unet_icassp_task2_finetune:
  ckpt_path: null
  load_weights_only: True

  defaults:
    - trainer: default
    - datamodule: icassp_task2
    - optimizer: adam
    - scheduler: icassp2_sd_finetune_32
    - algorithm: indoor
    - network: unet
    - callbacks: [ tqdm_progress_bar, model_checkpoint_0, model_checkpoint_every_4, val_alias_e3 ]
    - loggers: [ aim ]
    - strategy: null
    - _self_

  trainer:
    max_epochs: 32

  datamodule:
    train_samples_per_epoch: 3000

  callbacks:
    model_checkpoint_0:
      dirpath: runs/unet_icassp_task2_finetune/checkpoints/hard

  loggers:
    aim:
      experiment: v4_unet_icassp_task2_finetune

  algorithm:
    finetune:
      enable: True
