# @package _global_
name: inference
seed: 42
print_config: True
ignore_warnings: True

ckpt_paths: []  # List of checkpoint paths or directories to scan
gpu: 0
split:
  - test_0.02
  - test_0.5

predictions_dir: ${oc.env:PREDICTIONS_DIR}

defaults:
    - /datamodule@datamodule: mlsp
    - /algorithm@algorithm: indoor
    - /network@network: txunet
    - _self_

datamodule:
    inference: True
    batch_size: 1
    sparse_range: [0, 0]

hydra:
    run:
        dir: ${oc.env:OUTPUT_DIR}/inference/${now:%Y-%m-%d_%H-%M-%S.%f}
    job:
        chdir: True
