# @package _global_
name: inference
seed: 42
print_config: True
ignore_warnings: True

ckpt_paths: []  # List of checkpoint paths or directories to scan
gpu: 0
split:
  - test

predictions_dir: ${oc.env:PREDICTIONS_DIR}

defaults:
    - /datamodule@datamodule: icassp_task3
    - /algorithm@algorithm: indoor
    - /network@network: txunet
    - _self_

datamodule:
    inference: True
    batch_size: 1

hydra:
    run:
        dir: ${oc.env:OUTPUT_DIR}/inference/${now:%Y-%m-%d_%H-%M-%S.%f}
    job:
        chdir: True
