_target_: src.schedulers.wsd_s.WSDScheduler

warmup_steps: 250
stable_steps:
  - 2000
  - 2000
  - 4000
  - 8000
  - 16000
  - 32000
  - 64000
decay_steps:
  - 250
  - 500
  - 1000
  - 2000
  - 4000
  - 8000
  - 16000
peak_lr: 0.0003
last_epoch: -1
interval: step
frequency: 1