_target_: src.schedulers.wsd_s.WSDScheduler

warmup_steps: 40
stable_steps:
  - 120
  - 160
  - 320
  - 640
  - 1280
  - 2560
  - 5120
decay_steps:
  - 40
  - 40
  - 80
  - 160
  - 320
  - 640
  - 1280
peak_lr: 0.0003
last_epoch: -1
interval: step
frequency: 1