_target_: src.schedulers.wsd_s.WSDScheduler

warmup_steps: 130
stable_steps:
  - 1040
  - 1040
  - 2080
  - 4160
  - 8320
  - 16640
  - 33280
decay_steps:
  - 130
  - 260
  - 520
  - 1040
  - 2080
  - 4160
  - 8320
peak_lr: 0.0003
last_epoch: -1
interval: step
frequency: 1