_target_: src.schedulers.wsd_s.WSDScheduler

warmup_steps: 64
stable_steps:
  - 192
  - 256
  - 512
  - 1024
  - 2048
  - 4096
  - 8192
decay_steps:
  - 64
  - 64
  - 128
  - 256
  - 512
  - 1024
  - 2048
peak_lr: 0.0003
last_epoch: -1
interval: step
frequency: 1
