_target_: src.schedulers.wsd_s.WSDScheduler

warmup_steps: 20
stable_steps:
  - 60
  - 80
  - 160
  - 320
  - 640
  - 1280
  - 2560
decay_steps:
  - 20
  - 20
  - 40
  - 80
  - 160
  - 320
  - 640
peak_lr: 0.0003
last_epoch: -1
interval: step
frequency: 1