_target_: src.utils.every_n_epoch_checkpoint.EveryNEpochModelCheckpoint
monitor: null
save_top_k: -1
save_last: true
verbose: false
dirpath: checkpoints/every
filename: epoch_{epoch:04d}_every
auto_insert_metric_name: false
every_n_epochs: 10
