_target_: src.utils.scheduled_checkpoint.ScheduledEpochModelCheckpoint
monitor: null
save_top_k: -1
save_last: true
verbose: false
dirpath: /checkpoints/every
filename: epoch_{epoch:04d}_every
auto_insert_metric_name: false
schedule_epochs: [ 9, 19, 39, 79, 159, 319, 639 ]